# Generated by Django 4.2.11 on 2024-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=250, verbose_name='post_id')),
                ('message', models.TextField(verbose_name='message')),
                ('user_name', models.CharField(max_length=250, verbose_name='user_name')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('feedback_id', models.CharField(max_length=250, verbose_name='feedback_id')),
                ('video_list', models.TextField(verbose_name='video_list')),
                ('image_list', models.TextField(verbose_name='image_list')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'posts',
            },
        ),
    ]
