# Generated by Django 4.0 on 2024-03-14 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=250, verbose_name='user_id')),
                ('user_name', models.CharField(max_length=250, verbose_name='user_name')),
                ('user_url', models.CharField(max_length=250, verbose_name='user_url')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='posts',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.users', verbose_name='Users'),
            preserve_default=False,
        ),
    ]
