# Generated by Django 4.0 on 2024-03-14 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_users_posts_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='user_url',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_id',
        ),
    ]
