# Generated by Django 4.0 on 2024-03-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_rename_user_name_users_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigIntegerField(db_index=True, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
